# --- Basic options --- #

# Name of website
title: Mayukh Mukhopadhyay
##title-img: "/assets/img/logo12-removebg-preview.png"  #acm_logo_mm_2020.png
title-img: "/assets/img/acm_psm_mm.png"

# Short description of your site
description: My rantings on narrative and number.

# Your name to show in the footer
author: Mayukh Mukhopadhyay

# --- List of links in the navigation bar --- #

navbar-links:
 #ACM: "https://drive.google.com/file/d/1ZMTtp1wAqa3ReNmY2Q73AhDpcZkPdxnP/view?usp=sharing"
 Research Profile:
     - Web-of-Science: "https://www.webofscience.com/wos/author/record/AAQ-1861-2020"
     - Elsevier SSRN: "https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=4021262"
     - Google Scholar:  "https://scholar.google.co.in/citations?user=0fX4LNgAAAAJ&hl=en"
     - ORCID: "https://orcid.org/0000-0001-7733-7160"
     - Research Gate: "https://www.researchgate.net/profile/Mayukh_Mukhopadhyay2"
     - Scopus: "https://www.scopus.com/authid/detail.uri?authorId=57225169829"
     - Academy of Management: "https://connect.aom.org/aomthrivemicrositetemplate/profile?UserKey=992048f2-e3f1-4989-b8c5-018cd6f758c0"
     - Revise and Resubmit Podcast: "https://podcasts.apple.com/us/podcast/revise-and-resubmit-the-mayukh-show/id1770883122"

     
  #Author's home: "https://mayukhpsm.github.io/online-cv"
 About Me: "https://mayukhpsm.github.io/online-cv"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
avatar: "/assets/img/android-chrome-512x512.png"
#mugshot-290x290.png

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: "https://raw.githubusercontent.com/mayukhpsm/mayukhpsm.github.io/master/assets/img/acm_psm_mm.png"


# --- Footer options --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
# If you don't want to show a link to an RSS feed, set rss to "false".
social-network-links:
  email: "mayukh.psm@gmail.com"
  #facebook: #deanattali
  github: mayukhdifferent
  twitter: mayukhdifferent
  rss: false
#  reddit: yourname
  linkedin: mayukhpsm
#  xing: yourname
  stackoverflow: "4301387/mayukh-mukhopadhyay"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
  spotify: 1xyvX0vfCFtaLYEIqLUO88
#  telephone: +14159998888
#  steam: yourname
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname
#  mastodon: instance.url/@username
  quora: Mayukh-Mukhopadhyay-5
  medium: mayukhdifferent
  #gscholar: 0fX4LNgAAAAJ&hl
  #skype: "mayukh.psm"
  #whatsapp: "91****"

# --- General options --- #

# Select which social network share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "mayukhmukhopadhyay.com"

# Create a "tags" index page and make tags on each post clickable
link-tags: true

# Excerpt Word Length - Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# --- Colours / background image --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

#navbar-img: "/assets/img/white_bg.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/white_flakes.gif"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
#disqus: ""

# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
#fb_comment_id: ""

# To use Utterances comments: (0) uncomment the following section, (1) fill in
# "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# (3) Install the Utterances app in your repository https://github.com/apps/utterances
# See more details about the parameters below at https://utteranc.es/
#utterances:
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  issue-term: title   # Mapping between blog posts and GitHub issues
#  theme: github-light # Utterances theme
#  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

# To use Staticman comments, first invite `staticmanlab` as a collaborator to your repository and
# accept the invitation by going to `https://staticman3.herokuapp.com/v3/connect/github/<username>/<repo-name>`.
# Then uncomment the following section and fill in "repository", "branch", and "endpoint".
# If you want to use reCaptcha for staticman (optional for spam protection), then fill
# in the "siteKey" and "secret" parameters below and also in `staticman.yml`.
# See more details at https://staticman.net/
#staticman:
#  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
#  endpoint   : # URL of your own deployment, with a trailing slash (will fallback to a public GitLab instance) eg. https://<your-api>/v3/entry/github/
#  reCaptcha:
#    siteKey  : # Use your own site key, you need to apply for one on Google
#    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""


# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Asia/Calcutta"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 3

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: true # add estimated reading time on all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Mayukh Mukhopadhyay
# 2fc73a3a967e97599c9763d05e564189
